# Generated by Django 5.0 on 2023-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('richtexteditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor_content', models.CharField(max_length=255)),
            ],
        ),
    ]
